### PR TITLE
revised week 2 to flow together

### PR DESCRIPTION
**Pull request by paul-laskowski**

### CODE REVIEW

**Comment by anabranch** [comment]
LGTM

**Comment by paul-laskowski** [comment]
Thanks Bill!  I'm pretty happy with how this is fitting together.  I know I
said I'd be working on classes, but I think I want to try to assemble week
3 first, so we can see how more of the pieces fit.

Oh, when can you two meet online?  I can do tonight, tomorrow, or Wednesday
night.

**Comment by anabranch** [comment]
Monday at 7pm works fine! Let’s shoot for that since Kay can make that time too.




Bill

**Comment by paul-laskowski** [comment]
Great, see you guys then!

**Comment by kayashaolu** [comment]
Yep see you then!

**Pull request merged**
